version: '3'

services:
  registrar1:
    build:
      context: ./registrar
      dockerfile: Dockerfile
    container_name: registrar1
    hostname: registrar1
    restart: always
    networks: 
      - operation
  
  registrar2:
    build:
      context: ./registrar
      dockerfile: Dockerfile
    container_name: registrar2
    hostname: registrar2
    restart: always
    networks: 
      - operation

  writter1:
    build:
      context: ./writter
      dockerfile: Dockerfile
    container_name: writter1
    hostname: writter
    restart: always
    networks: 
      - operation
  
  writter2:
    build:
      context: ./writter
      dockerfile: Dockerfile
    container_name: writter2
    hostname: writter2
    restart: always
    networks: 
      - operation
  
  writter3:
    build:
      context: ./writter
      dockerfile: Dockerfile
    container_name: writter3
    hostname: writter3
    restart: always
    networks: 
      - operation

  nats:
    image: nats:latest
    container_name: nats
    hostname: nats
    restart: always
    networks: 
      - operation
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - registrar1
      - registrar2
      - writter1
      - writter2
      - writter3
      - nats
    networks:
      - operation
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: joy
      MYSQL_USER: joy
      MYSQL_PASSWORD: 1234
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - operation

networks:
  operation:
    driver: bridge